# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'TestProject' do
	pod "AFNetworking", "~> 2.0"
	pod 'Gloss', '~> 0.6'
    pod 'Alamofire', '~> 3.0'
end

